spring:
  application:
    name: calenderyBack

  datasource:
    url: ${DATA_BASE_URL}
    username: ${DATA_BASE_USERNAME}
    password: ${DATA_BASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: martinandraderuben@gmail.com
    password: qeok apwb rqqw iius
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG


