spring:
  application:
    name: calenderyBack

  datasource:
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.hplwhrjrasmhwsjtawht
    password: zUFrhGFpvmDliKST
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: martinandraderuben@gmail.com
    password: qeok apwb rqqw iius
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
